name: quarto_docs
channels:
  - conda-forge
dependencies:
  - bash_kernel
  - gh
  - ipykernel
  - jupyter_client
  - make
  - nbclient
  - nbformat
  - pip
  - python
  - python-pptx
  - pyyaml
  - quarto
  - pip:
      - pipdeptree
